apiVersion: 1

datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086

    database: metrics
    user: grafana

    jsonData:
      httpMode: GET

    secureJsonData:
      password: ${INFLUXDB_TOKEN}

    isDefault: false
    editable: false