apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy

    url: https://prometheus:9090

    basicAuth: true
    basicAuthUser: grafana

    jsonData:
      tlsAuthWithCACert: true
      tlsSkipVerify: false

    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_BASIC_AUTH_PASSWORD}
      tlsCACert: ${PROMETHEUS_CA_CERT}

    isDefault: true
    editable: false
