upstream grafana_backend {
    server grafana-1:3000 max_fails=3 fail_timeout=10s;
    server grafana-2:3000 max_fails=3 fail_timeout=10s;
}

server {
    listen 80;
    server_name grafana.local;

    location = /nginx_status {
        stub_status;

        allow 127.0.0.1;
        allow 172.16.0.0/12;
        deny all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name grafana.local;

    ssl_certificate /etc/nginx/certs/grafana.crt;
    ssl_certificate_key /etc/nginx/certs/grafana.key;

    location / {
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass http://grafana_backend;
    }

    location /api/live/ {
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass http://grafana_backend;
    }
}